// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/21/2025, 6:02:23 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/workspace/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/workspace/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/workspace/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/workspace/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/workspace/plugins/**/*.{js,ts,mjs}","/home/workspace/composables/**/*.{js,ts,mjs}","/home/workspace/utils/**/*.{js,ts,mjs}","/home/workspace/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/workspace/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/workspace/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/workspace/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;